### ISSUE TITLE
Crash server Mountables 1-24.jar

### ISSUE THREAD

**Issue by RedneTwo** [LukeGrahamLandry/mountables-mod#1]
06.06 13:22:10 [Server] INFO Suspected Mods: Forge (forge), Forge (forge)[11:22:10] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
06.06 13:22:10 [Server] INFO net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
06.06 13:22:10 [Server] INFO Mountables (mountables) has failed to load correctly
06.06 13:22:10 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/model/EntityModel
06.06 13:22:10 [Server] INFO ]
06.06 13:22:10 [Server] INFO at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?] {re:classloading}
06.06 13:22:10 [Server] INFO at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
06.06 13:22:10 [Server] INFO at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[forge:?] {re:classloading}
06.06 13:22:10 [Server] INFO at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
06.06 13:22:10 [Server] INFO at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
06.06 13:22:10 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
06.06 13:22:10 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
06.06 13:22:10 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
06.06 13:22:10 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
06.06 13:22:10 [Server] INFO at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.1.25.jar:36.1] {}
06.06 13:22:10 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
06.06 13:22:10 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
06.06 13:22:10 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
06.06 13:22:10 [Server] INFO at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
06.06 13:22:10 [Server] INFO at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
06.06 13:22:10 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.1.25.jar:?] {re:classloading}
06.06 13:22:10 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.1.25.jar:?] {re:classloading}
06.06 13:22:10 [Server] INFO at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.1.25.jar:?] {re:classloading}

**Comment by LukeGrahamLandry** [comment]
Should be fixed on version 1.25 :)
Shall be available whenever curseforge approves it.
